### ISSUE TITLE
Introduce support of nested attributes via dot notation

### ISSUE THREAD

**Issue by kimrgrey** [trickstersio/performify#22]
When you define input attributes in schema `performify` automatically creates accessors for those attributes for you. Pretty nice feature. However if attributes are nested you don't have such benefit.

Here is an example how it is supposed to work:

```ruby
class SomeService < Performify::Base
  schema do
    required(:admin).schema do
      required(:email).filled(:str?)
    end
  end

  def execute!
    # right now you can do only admin[:email] which is not consistent 
    super { User.create(email: admin.email) }
  end
end
```

**Comment by groony** [comment]
@kimrgrey 
You can already get it by
```ruby
inputs[:admin][:email]
```

**Comment by kimrgrey** [comment]
@groony sure, you can also get it as `admin[:email]`. But what I expect to see is struct and not hash in such case.
