### ISSUE TITLE
NameError: uninitialized constant Dry::Validation::Schema

### ISSUE THREAD

**Issue by vsrboth** [trickstersio/performify#32]
Keep getting the following error no matter what:

```
NameError: uninitialized constant Dry::Validation::Schema
from .../gems/performify-0.11.0/lib/performify/validation.rb:13:in `schema'
```

Here are the sample codes

```
class SomeService < Performify::Base
  schema do
     required(:claim_id).value(:integer)
  end

  def execute!
  end
end
```

service = SomeService.new(current_user, claim_id: 1)

**Comment by vsrboth** [comment]
Problem is pretty straight forward. Bundler keeps installing `dry-validation-1.1.0`.

**Comment by kimrgrey** [comment]
Fixed by latest PR. Please, switch to version `1.0.0`. Should work now. Thanks for your report!
